### PR TITLE
Beginnings of I18N in QM

### PR DESCRIPTION
**Pull request by Antweeker**
Basically, I added some objects on the window "en" and "zh" where en is
english and zh is chinese. I messed with the headerview template and
chose to implment a simple I18N formatting system. This is the basic
blocks for I18N.

Am I heading down the correct path here? Should we use a I18n library? Also, forgive the chinese; it came from google translate.

### CODE REVIEW

**Comment by Antweeker** [comment]
Also, I need a way to re-render the header view + config view after changing the lang in the configView. I'm trying to wrap my head around that part, but everything happens in the router.

**Comment by Antweeker** [comment]
Ugh, this work is tedious. I did what I did for the headerView to all the views that we use currently.

**Comment by Antweeker** [comment]
Do the extra commas break your stuff? If so I'll stop using them.

**Comment by ed-xj** [comment]
it's working now dude. after you change the language select, the whole ui changed to the selected lang without refresh. check it out, it's magic!

**Comment by Antweeker** [comment]
Looks good man. Should I correct the merge conflicts, add the botcom page to the configs and merge?

**Comment by ed-xj** [comment]
yes

**Pull request merged**
