### PR TITLE
Botcom ui attempt

### PR DESCRIPTION
**Pull request by Antweeker**
Added the botom ui view.

First attempt at botcom.

Obviously, we can tweak a lot of stuff here, but this is a rough estimate on what it'll look like when it's done.

### CODE REVIEW

**Comment by Antweeker** [comment]
The Height on the right side is too big. We need a way to shorten it.

**Comment by Antweeker** [comment]
For the height, I think we can put the "perch-inside" + "high-low" choices on the same height, next to eachother. What do you think @ed-xj ?

**Comment by ed-xj** [comment]
the ui looks good to me. for the height on the right side, why don't we just increase the height of the listbox on the left until the bottom aligns? make sense? I think what we have now is already fine. I'll get more feedback Monday so let's wait a bit here. :shipit:

**Comment by Antweeker** [comment]
The left is actually perfect when on a 1024 screen.

**Pull request merged**
